version: '3'
services:
  nuxt:
    # Dockerfileの場所
    build: .
    working_dir: /src
    # command: yarn run dev
    # ホストOSとコンテナ内でソースコードを共有する
    volumes:
      - .:/src
    # コンテナ内部の3000を外部から5000でアクセスする
    ports:
      - 5000:3000
    # コンテナ起動後、StatusがExitにならないようttyの設定
    tty: true